### ISSUE TITLE
Unstable connection and random disconnections

### ISSUE THREAD

**Issue by VolBog** [binance4j/binance4j#1]
**Describe the bug**
Looks like, after certain use of the WebSocket library, I have the random disconnections from the Binance API server. Looks like, after 5-10 hours of work, the Websocket client is still in the memory but doesn't obtain data. 

I use the standard method from Binance4J-strategy, but a little bit changes it for saving data to the Database. 
`public void watch(String symbols, CandlestickInterval interval, ApiStrategyCallback callback)`

Maybe I need to handle WebSockets in the List and check if they are still alive?

**Comment by vivienld** [comment]
Version 1.4.3 brings keepAlive functionalities

- Every `WebsocketClient` automatically reconnects if connection is lost (can be changed).
- Every `WebsocketClient` times out after a certain amount of time without response (3min by default, can be changed). Coupled with auto reconnection, streams should always be on.
- `WebsocketCandlestickClient` automatically sets noResponseTimeout according to defined CandlestickInterval.
- `UserDataWebsocketClient` automatically extends listenKey lifespan every 30 minutes. (can be changed)

[Documentation](https://binance4j.github.io/binance4j-documentation/docs/Websocket)

Feel free to give me feedback. I will close the issue without answer at the end of the month.

**Comment by VolBog** [comment]
Now, everything looks ok. 
I was just updated for the new version.
I'll watch for a few days, if the bug repeats, I'll write here.
Thank you for promptly resolving the issue.

**Comment by vivienld** [comment]
👍

**Comment by vivienld** [comment]
Version 1.7.0 adds live trading on multiple symbols, see [documentation](https://binance4j.github.io/binance4j-documentation/docs/Strategy#watch-multiple-symbols).

**Comment by VolBog** [comment]
So looks like the 1.4.3 version still loses connection after a certain period of time, like 2-3 days. 
According to the documentation
```
 A single connection to stream.binance.com is only valid for 24 hours; expect to be disconnected at the 24 hour mark.

    The websocket server will send a ping frame every 3 minutes. If the websocket server does not receive a pong frame back from the connection within a 10 minute period, the connection will be disconnected. Unsolicited pong frames are allowed.
```
So after 24 hours, it works ok, but later just loses connection. 
I will try to update to the last version and test again.

**Comment by vivienld** [comment]
Did it call onFailure or did it juste close the stream without exception?

**Comment by vivienld** [comment]
Can you show me your strategy script?

**Comment by vivienld** [comment]
I will run a strategy on a raspi until it closes and log the results to see and come back to you

**Comment by VolBog** [comment]
So I don't know what the reason for this behavior
I don't use some strategy,  I just rewrite the watch method to make some signals depend on the market structure, save it to the DataBase and send it to the discord channel. 
```

public void watch(String symbols, CandlestickInterval interval, ApiStrategyCallback callback, boolean isHTF, String discordChannelId) {
        BarSeries series = new BaseBarSeries();
        BarSeries historical = null;
        MarketStructure marketStructure = new MarketStructure();
        try {
            MarketClient marketClient = MarketClient.getInstance();

            marketStructure.setSymbol(symbols);
            marketStructure.setInterval(interval);
            historical = marketClient.getBarSeries(symbols, interval);
            for (int i = 0; i < historical.getBarCount() - 1; i++) {
                if (isHTF) {
                    HTFSignals(historical, symbols, interval, i);
                } else {
                    LTFSignal(marketStructure, historical, symbols, i, interval);
                }
            }
        } catch (ApiException e) {
            e.printStackTrace();
        }
        if (historical != null) {
            for (int i = 0; i < historical.getBarCount() - 1; i++) { // we scip last bar because it is not complete
                if (historical.getBar(i).getEndTime().isAfter(ZonedDateTime.now().minus(1, ChronoUnit.MONTHS))) {
                    series.addBar(historical.getBar(i));
                }
            }
        }
        System.out.println("Watching " + symbols + " " + interval);
        System.out.println("length of historical data: " + series.getBarCount());
        Duration duration = DurationService.convert(interval);
        this.wsClient = new WebsocketCandlestickClient(symbols, interval);
        System.out.println("Connecting to " + wsClient.toString());
        this.wsClient.onOpen((cb) -> {
            callback.getOnOpenConsumer().accept(cb);
            //  System.out.println("ON OPEN");
        });

        //
        this.wsClient.onClosed((cb) -> {
                    callback.getOnClosedConsumer().accept(cb);
                }
        );
        this.wsClient.onClosing((cb) -> {
            callback.getOnClosingConsumer().accept(cb);
//            System.out.println("ON CLOSING");
        });
        this.wsClient.onFailure((cb) -> {
            callback.getOnFailureConsumer().accept(cb);
//            System.out.println("ON FAILURE");
        });
        this.wsClient.onMessage((cb) -> {
            Bar bar = BarService.convert(cb, duration);
            callback.getOnMessageConsumer().accept(bar);
            if (cb.getIsBarFinal().booleanValue()) {
                series.addBar(bar);
                int lastIndex = series.getBarCount() - 1;
                // check if the bar forming the OB
                Figures figures = Figures.getInstance();
                if (isHTF) {
                       HTFSignals(series, symbols, interval, lastIndex);
                } else {
                        LTFSignal(marketStructure, series, symbols, lastIndex, discordChannelId, interval);
                }
            }
            //System.out.println("ON MESSAGE");
        });
        this.wsClient.open();
    }

```

At this time I still see Threads that regard the Websocket in the htop tasks manager.

**Comment by vivienld** [comment]
`BaseTradingStrategy` was designed to receive an `ApiStrategyCallback` that already handles all the stream events. Rewriting the source code of the watch method doesn't seem the right way to go and can only lead to code instability. 

Please read documentation about creating a strategy 
[here](https://binance4j.github.io/binance4j-documentation/docs/Strategy#write-a-strategy) 
and handling stream events 
[here](https://binance4j.github.io/binance4j-documentation/docs/Strategy#live-trade).

Since this morning, my websockets are all active. I will let them run until sunday.

Be notified that realeases before 1.7.0 had a bug that made multiple symbols share the same barSeries leading to strategy inefficiency. 
Updating to this version corrects this issue. 

Regards.

**Comment by VolBog** [comment]
Thanks for your response. 
But I use the price action system where I synchronized HTF with LTF. 
So I have some zone in HTF and see if I have a specific situation on the LTF. 
According to the documentation I just can use HTF indicators.

**Comment by vivienld** [comment]
If ta4j has this indicator yes, else you will have to implement it

**Comment by vivienld** [comment]
According to my logs, the binance server tries to close the connection after 2 days and 14 hours 
but only onClosing is triggered and not onClosed.

This explains why the client won't reconnect since it reconnects after being closed.
And it explains why you still see the websocket processes.

The idea here is that i implement a timer that will call onClosed if not called after some time.

v1.8.0 should come out tomorrow with a patch. I will rerun a live trade to be sure this time it works.

Regards.

**Comment by vivienld** [comment]
```java
2022-05-29 04:15:36.154 INFO [OkHttp https://stream.binance.com:9443/...] 
[com.binance4j.strategy.App.lambda$main$4(App.java:24)] - message : SymbolBar(symbol=BNBBTC)
2022-05-29 04:15:39.415 INFO [OkHttp https://stream.binance.com:9443/...] 
[com.binance4j.strategy.App.lambda$main$4(App.java:24)] - message : SymbolBar(symbol=BNBBTC)
2022-05-29 04:15:51.745 INFO [OkHttp https://stream.binance.com:9443/...] 
[com.binance4j.strategy.App.lambda$main$4(App.java:24)] - message : SymbolBar(symbol=BNBBTC)
2022-05-29 04:15:53.985 INFO [OkHttp https://stream.binance.com:9443/...] 
[com.binance4j.strategy.App.lambda$main$4(App.java:24)] - message : SymbolBar(symbol=BNBBTC)
2022-05-29 04:15:56.984 INFO [OkHttp https://stream.binance.com:9443/...] 
[com.binance4j.strategy.App.lambda$main$4(App.java:24)] - message : SymbolBar(symbol=BNBBTC)

// The server suddenly tries to close the stream

2022-05-29 04:16:01.769 INFO [OkHttp https://stream.binance.com:9443/...] 
[com.binance4j.strategy.App.lambda$main$1(App.java:20)] - closing

//stream not closed (?!)


//5 minutes later we didn't receive any data so the client triggers onFailure and should close the strean and reconnect 
//but since the stream is already trying to close, onClosing and onClosed are not triggered.

2022-05-29 04:20:57.006 ERROR [Timer-0] 
[com.binance4j.strategy.App.lambda$main$3(App.java:22)] - failure : 403 - UNKNOWN - Response timeout : no data received for 300 seconds

// no close event triggered ...
```

**Comment by vivienld** [comment]
Version 2 is out and websocket stability has been tested with live trading active for 2 weeks.
This is a breaking update in every way (naming, layer abstraction...)
see [documentation](https://binance4j.github.io/binance4j/binance4j-documentation/docs/websocket)
