### ISSUE TITLE
NoSuchMethodError - Class MarketDataClient

### ISSUE THREAD

**Issue by rkyshz** [binance4j/binance4j#2]
Exception in thread "main" java.lang.NoSuchMethodError: java.util.List.of(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/List;
	at com.binance4j.core.request.RestClient.<clinit>(RestClient.java:36)

at

MarketDataClient client = new MarketDataClient(API_KEY, API_SECRET);

**Comment by vivienld** [comment]
Use java 8+

**Comment by rkyshz** [comment]
I am using java 8. Also tried with Java 11. Doesn't work

**Comment by vivienld** [comment]
Yes my bad it's a method introduced in java 9. I was using jdk 17 in development and the error was not showing. I am correcting this in 2.0.0 coming next week.

**Comment by vivienld** [comment]
You can temporarily compile the sources by changing List.of with Arrays.asList

**Comment by vivienld** [comment]
version 1.7.4 is fixing method issues and will be the last 1.x version.
